newsletter-platform/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#root'
  resources :newsletters
  resources :issues
  resources :accounts
  resources :account_links
  resources :memberships
  resource :billing
  resources :login_links
  get 'dashboard', to: 'pages#dashboard'
  
  # localhost:3000
  post '/webhooks/:source', to: 'webhooks#create'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

newsletter-platform/app/models/account.rb
class Account < ApplicationRecord
  belongs_to :author, class_name: 'User'
end

newsletter-platform/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

newsletter-platform/app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :reader, class_name: 'User'
end

newsletter-platform/app/models/event.rb
class Event < ApplicationRecord
    enum status: {
        pending: 0,
        processing: 1,
        processed: 2,
        failed: 3,
    }
end

newsletter-platform/app/models/issue.rb
class Issue < ApplicationRecord
  belongs_to :newsletter
end

newsletter-platform/app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :newsletter
  belongs_to :reader, class_name: 'User'
end

newsletter-platform/app/models/newsletter.rb
class Newsletter < ApplicationRecord
  belongs_to :author, class_name: 'User'

  has_many :issues
  has_many :memberships, dependent: :destroy
end

newsletter-platform/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :trackable

  has_many :newsletters, foreign_key: :author_id, dependent: :destroy
  has_many :issues, through: :newsletters
  has_many :accounts, foreign_key: :author_id, dependent: :destroy

  has_many :memberships, foreign_key: :reader_id, dependent: :destroy
  has_many :customers, foreign_key: :reader_id, dependent: :destroy
  has_many :subscribed_newsletters, through: :memberships, source: :newsletter

  def active_subscribed_newsletters
    subscribed_newsletters.where('memberships.status = ?', 'active')
  end

  def stripe_customer_id
    if customers.empty?
      customer = Stripe::Customer.create(
        email: email,
      )
      customers.create!(stripe_customer_id: customer.id)
    end

    customers.first.stripe_customer_id
  end

  def stripe_account_id
    default_account&.stripe_account_id
  end

  def default_account
    accounts.find_by(default_account: true)
  end
end

newsletter-platform/app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :authenticate_user!

  def index
    @issues = current_user.issues.includes(:newsletter)
  end

  def new
    @issue = Issue.new
    # @issue = Issue.new(published_at: Time.now)

  end

  def create
    @issue = current_user.issues.new(issue_params)
    if @issue.save
      redirect_to issues_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @issue = Issue.find(params[:id])
  end


  def edit
    @issue = current_user.issues.find(params[:id])
  end

  def update
    @issue = current_user.issues.find(params[:id])
    if @issue.update(issue_params)
      redirect_to issues_path
    else
      render :edit
    end
  end

  private
  def issue_params
    params.require(:issue).permit(:newsletter_id, :subject, :content, :published_at )
  end
end

newsletter-platform/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  layout 'marketing'

  def root
  end

  def dashboard
    @subscribed_newsletters = current_user.active_subscribed_newsletters
    @newsletters = Newsletter.where.not(id: @subscribed_newsletters.pluck(:id))
    @issues = Issue.where(newsletter: @subscribed_newsletters).order(created_at: :desc)

    render 'dashboard', layout: 'application'
  end
end

newsletter-platform/app/helpers/account_links_helper.rb
module AccountLinksHelper
end

newsletter-platform/app/helpers/accounts_helper.rb
module AccountsHelper
end

newsletter-platform/app/helpers/application_helper.rb
module ApplicationHelper
end

newsletter-platform/app/helpers/billings_helper.rb
module BillingsHelper
end

newsletter-platform/app/helpers/issues_helper.rb
module IssuesHelper
end

newsletter-platform/app/helpers/login_links_helper.rb
module LoginLinksHelper
end

newsletter-platform/app/helpers/memberships_helper.rb
module MembershipsHelper
end

newsletter-platform/app/helpers/newsletters_helper.rb
module NewslettersHelper
end

newsletter-platform/app/helpers/pages_helper.rb
module PagesHelper
end

newsletter-platform/app/helpers/webhooks_helper.rb
module WebhooksHelper
end

newsletter-platform/app/views/layouts/application.html.erb
<!DOCTYPE html>
  <head>
    <title>NewsletterPlatform</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.1/flowbite.min.css" rel="stylesheet" />
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
  

    
<button data-drawer-target="sidebar-multi-level-sidebar" data-drawer-toggle="sidebar-multi-level-sidebar" aria-controls="sidebar-multi-level-sidebar" type="button" class="inline-flex items-center p-2 mt-2 ml-3 text-sm text-gray-500 rounded-lg sm:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600">
   <span class="sr-only">Open sidebar</span>
   <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
      <path clip-rule="evenodd" fill-rule="evenodd" d="M2 4.75A.75.75 0 012.75 4h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 4.75zm0 10.5a.75.75 0 01.75-.75h7.5a.75.75 0 010 1.5h-7.5a.75.75 0 01-.75-.75zM2 10a.75.75 0 01.75-.75h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 10z"></path>
   </svg>
</button>

<aside id="sidebar-multi-level-sidebar" class="fixed top-0 left-0 z-40 w-50 h-screen transition-transform -translate-x-full sm:translate-x-0" aria-label="Sidebar">
   <div class="h-full px-3 py-4 overflow-y-auto bg-yellow-50 dark:bg-gray-800">
     <%if current_user%>
   <h3 class="flex pt-2 justify-center text-gray-600 text-3xl font-bold mb-4">
   📰<%=  current_user.name.capitalize %>📰
   </h3>
   <% end %>
      <ul class="flex flex-col justify-between pt-10 pl-5 space-y-8 font-medium">
      
         <li>
            <a href="/dashboard" class="flex items-center p-2 text-gray-600 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
               <svg class="w-5 h-5 text-gray-600 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 21">
                  <path d="M16.975 11H10V4.025a1 1 0 0 0-1.066-.998 8.5 8.5 0 1 0 9.039 9.039.999.999 0 0 0-1-1.066h.002Z"/>
                  <path d="M12.5 0c-.157 0-.311.01-.565.027A1 1 0 0 0 11 1.02V10h8.975a1 1 0 0 0 1-.935c.013-.188.028-.374.028-.565A8.51 8.51 0 0 0 12.5 0Z"/>
               </svg>
               <span class="ml-3">Dashboard</span>
            </a>
         </li>
         <li>
            <a href="/newsletters" class="flex items-center w-full p-2 text-base text-gray-600 transition duration-75 rounded-lg group hover:bg-gray-100 dark:text-white dark:hover:bg-gray-700" aria-controls="dropdown-example" data-collapse-toggle="dropdown-example">
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5 text-gray-600 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white">
  <path stroke-linecap="round" stroke-linejoin="round" d="M21.75 6.75v10.5a2.25 2.25 0 01-2.25 2.25h-15a2.25 2.25 0 01-2.25-2.25V6.75m19.5 0A2.25 2.25 0 0019.5 4.5h-15a2.25 2.25 0 00-2.25 2.25m19.5 0v.243a2.25 2.25 0 01-1.07 1.916l-7.5 4.615a2.25 2.25 0 01-2.36 0L3.32 8.91a2.25 2.25 0 01-1.07-1.916V6.75" />
</svg>

                  <span class="flex-1 ml-3 text-left whitespace-nowrap">Newsletters</span>
                  
            </a>
         </li>
         <li>
            <a href="/issues" class="flex items-center p-2 text-gray-600 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
               <svg class="flex-shrink-0 w-5 h-5 text-gray-600 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 18 18">
                  <path d="M6.143 0H1.857A1.857 1.857 0 0 0 0 1.857v4.286C0 7.169.831 8 1.857 8h4.286A1.857 1.857 0 0 0 8 6.143V1.857A1.857 1.857 0 0 0 6.143 0Zm10 0h-4.286A1.857 1.857 0 0 0 10 1.857v4.286C10 7.169 10.831 8 11.857 8h4.286A1.857 1.857 0 0 0 18 6.143V1.857A1.857 1.857 0 0 0 16.143 0Zm-10 10H1.857A1.857 1.857 0 0 0 0 11.857v4.286C0 17.169.831 18 1.857 18h4.286A1.857 1.857 0 0 0 8 16.143v-4.286A1.857 1.857 0 0 0 6.143 10Zm10 0h-4.286A1.857 1.857 0 0 0 10 11.857v4.286c0 1.026.831 1.857 1.857 1.857h4.286A1.857 1.857 0 0 0 18 16.143v-4.286A1.857 1.857 0 0 0 16.143 10Z"/>
               </svg>
               <span class="flex-1 ml-3 whitespace-nowrap">issues</span>
            </a>
         </li>
         <li>
            <a href="/accounts" class="flex items-center p-2 text-gray-600 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
               <svg class="flex-shrink-0 w-5 h-5 text-gray-600 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                  <path d="m17.418 3.623-.018-.008a6.713 6.713 0 0 0-2.4-.569V2h1a1 1 0 1 0 0-2h-2a1 1 0 0 0-1 1v2H9.89A6.977 6.977 0 0 1 12 8v5h-2V8A5 5 0 1 0 0 8v6a1 1 0 0 0 1 1h8v4a1 1 0 0 0 1 1h2a1 1 0 0 0 1-1v-4h6a1 1 0 0 0 1-1V8a5 5 0 0 0-2.582-4.377ZM6 12H4a1 1 0 0 1 0-2h2a1 1 0 0 1 0 2Z"/>
               </svg>
               <span class="flex-1 ml-3 whitespace-nowrap">Payments</span>
            </a>
         </li>
         <li>
            <a href="/billing" class="flex items-center p-2 text-gray-600 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
               <svg class="flex-shrink-0 w-5 h-5 text-gray-600 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 18">
                  <path d="M14 2a3.963 3.963 0 0 0-1.4.267 6.439 6.439 0 0 1-1.331 6.638A4 4 0 1 0 14 2Zm1 9h-1.264A6.957 6.957 0 0 1 15 15v2a2.97 2.97 0 0 1-.184 1H19a1 1 0 0 0 1-1v-1a5.006 5.006 0 0 0-5-5ZM6.5 9a4.5 4.5 0 1 0 0-9 4.5 4.5 0 0 0 0 9ZM8 10H5a5.006 5.006 0 0 0-5 5v2a1 1 0 0 0 1 1h11a1 1 0 0 0 1-1v-2a5.006 5.006 0 0 0-5-5Z"/>
               </svg>
               <span class="flex-1 ml-3 whitespace-nowrap">Billing</span>
            </a>
         </li>
         
      </ul>
    
   </div>

</aside>


 <div class="grid grid-cols-4 gap-4">
 
 <div class="col-span-1 ">
 </div>
 <div class="col-span-3 ">
	<%= yield %>
 </div>
</div>
 
<script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.1/flowbite.min.js"></script>

   </body>
  
</html>

newsletter-platform/app/views/layouts/devise.html.erb
<!DOCTYPE html>
  <head>
    <title>NewsletterPlatform</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.1/flowbite.min.css" rel="stylesheet" />
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
  
    <%= yield %>
 
<script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.1/flowbite.min.js"></script>
   </body>
</html>

newsletter-platform/app/views/layouts/marketing.html.erb
<!DOCTYPE html>
  <head>
    <title>NewsletterPlatform</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.1/flowbite.min.css" rel="stylesheet" />
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
  
    <%= yield %>
 
<script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.1/flowbite.min.js"></script>
   </body>
</html>

newsletter-platform/app/views/pages/dashboard.html.erb
<div class="flex grid grid-cols-2 gap-4">

	<!-- Each <div> is a single column.
	Place some content inside to see the effect. -->
	<div>
<div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="flex flex-col text-3xl p-5 text-center justify-center">
      Newsletters
    </div>

    <div class="inline-block min-w-full py-2 sm:px-6 lg:px-8">
      <div class="overflow-hidden">
        <table class="min-w-full text-center text-sm font-light">
        <thead class="border-b font-medium dark:border-neutral-500">
  <tr>
    <th scope="col" class="px-6 py-4" colspan="2">
      <p class="text-center">Subbed Newsletters!</p>
    </th>
  </tr>
</thead>
          <thead class="border-b font-medium dark:border-neutral-500">
            <tr>
              
              <th scope="col" class="px-6 py-4">Title</th>
              <th scope="col" class="px-6 py-4"><span>View</span></th>
            </tr>
          </thead>
          <tbody>
            <% @subscribed_newsletters.each do |n| %>
            <tr class="border-b dark:border-neutral-500">
              <td class="whitespace-nowrap px-6 py-4 font-medium">
                <%= n.title %>
              </td>
              <td class="whitespace-nowrap px-6 py-4">
                <a href="<%= newsletter_path(n) %>" class="ml-5 inline-block px-2 py-2 font-semibold text-white bg-blue-500 rounded-md hover:bg-blue-600 transition duration-300 ease-in-out">View</a>

              </td>
            </tr>
            <% end %>
            <thead class="border-b font-medium dark:border-neutral-500">
            <tr>
              
              <th scope="col" class="px-6 py-4"></th>
              <th scope="col" class="px-6 py-4"><span></span></th>
            </tr>
          </thead>
            <thead class="border-b font-medium dark:border-neutral-500">
  <tr>
    <th scope="col" class="px-6 py-4" colspan="2">
      <p class="text-center">Search for Newsletters!</p>
    </th>
  </tr>
</thead>
            <thead class="border-b font-medium dark:border-neutral-500">
            <tr>
              
              <th scope="col" class="px-6 py-4">Title</th>
              <th scope="col" class="px-6 py-4"><span>View</span></th>
            </tr>
          </thead>
          

             <% @newsletters.each do |n| %>
            <tr class="border-b dark:border-neutral-500">
              <td class="whitespace-nowrap px-6 py-4 font-medium">
                <%= n.title %>
              </td>
              <td class="whitespace-nowrap px-6 py-4">
                <a href="<%= newsletter_path(n) %>" class="ml-5 inline-block px-2 py-2 font-semibold text-white bg-blue-500 rounded-md hover:bg-blue-600 transition duration-300 ease-in-out">View</a>

              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  </div>

	<div>
<div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="flex flex-col text-3xl p-5 text-center justify-center">
      Issues
    </div>

    <div class="inline-block min-w-full py-2 sm:px-6 lg:px-8">
      <div class="overflow-hidden">
        <table class="min-w-full text-center text-sm font-light">
            <% if @issues.empty? %>
            Subscribe to a Newsletter to see issues!
            <% else %>
        <thead class="border-b font-medium dark:border-neutral-500">
  <tr>
    <th scope="col" class="px-6 py-4" colspan="2">
      <p class="text-center">Read on, friend!</p>
    </th>
  </tr>
</thead>
          <thead class="border-b font-medium dark:border-neutral-500">
            <tr>
              
              <th scope="col" class="px-6 py-4">Title</th>
              <th scope="col" class="px-6 py-4"><span>Edit</span></th>
            </tr>
          </thead>
          <tbody>
              <% @issues.each do |n| %>
              <tr class="border-b dark:border-neutral-500">
                <td class="whitespace-nowrap px-6 py-4 font-medium">
                  <%= n.subject %>
                </td>
                <td class="whitespace-nowrap px-6 py-4">
                  <a href="<%= issue_path(n) %>" class="ml-5 inline-block px-2 py-2 font-semibold text-white bg-blue-500 rounded-md hover:bg-blue-600 transition duration-300 ease-in-out">Read</a>

                </td>
              </tr>
              <% end %>
          </tbody>
            <% end %>
        </table>
      </div>
    </div>

    

  </div>
  </div>

</div>

newsletter-platform/app/views/pages/root.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>
      Tailwind Starter Template - Landing Page Template: Tailwind Toolbox
    </title>
    <meta name="description" content="Simple landind page" />
    <meta name="keywords" content="" />
    <meta name="author" content="" />
    <link rel="stylesheet" href="https://unpkg.com/tailwindcss@2.2.19/dist/tailwind.min.css"/>
    <!--Replace with your tailwind.css once created-->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700" rel="stylesheet" />
    <!-- Define your gradient here - use online tools to find a gradient matching your branding-->
    <style>
      .gradient {
        background: linear-gradient(90deg, #d53369 0%, #daae51 100%);
      }
    </style>
  </head>
  <body class="leading-normal h-screen tracking-normal text-white gradient" style="font-family: 'Source Sans Pro', sans-serif;">
    <!--Nav-->
    
    <!--Hero-->
    <div class="pt-24">
      <div class="container px-3 mx-auto flex flex-wrap flex-col md:flex-row items-center">
        <!--Left Col-->
        <div class="flex flex-col w-full md:w-2/5 justify-center items-start text-center md:text-left">
          <p class="uppercase tracking-loose w-full">Write on friends!</p>
          <h1 class="my-4 text-5xl font-bold leading-tight">
            Become an Author today!
          </h1>
         
                <% if user_signed_in? %>
                    <a href="/newsletters" class="mx-auto lg:mx-0 hover:underline bg-white text-gray-800 font-bold rounded-full my-6 py-4 px-8 shadow-lg focus:outline-none focus:shadow-outline transform transition hover:scale-105 duration-300 ease-in-out z-50">
                        Go to dashboard
                    </a>
                <% else %>
                    <a href="/users/sign_up" class="mx-auto lg:mx-0 hover:underline bg-white text-gray-800 font-bold rounded-full my-6 py-4 px-8 shadow-lg focus:outline-none focus:shadow-outline transform transition hover:scale-105 duration-300 ease-in-out z-50">
                         Get Started
                    </a>
                <% end %> 
        </div>
        <!--Right Col-->
        
      </div>
    </div>
    <div class="relative -mt-12 lg:-mt-24">
      <svg viewBox="0 0 1428 174" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
        <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
          <g transform="translate(-2.000000, 44.000000)" fill="#FFFFFF" fill-rule="nonzero">
            <path d="M0,0 C90.7283404,0.927527913 147.912752,27.187927 291.910178,59.9119003 C387.908462,81.7278826 543.605069,89.334785 759,82.7326078 C469.336065,156.254352 216.336065,153.6679 0,74.9732496" opacity="0.100000001"></path>
            <path
              d="M100,104.708498 C277.413333,72.2345949 426.147877,52.5246657 546.203633,45.5787101 C666.259389,38.6327546 810.524845,41.7979068 979,55.0741668 C931.069965,56.122511 810.303266,74.8455141 616.699903,111.243176 C423.096539,147.640838 250.863238,145.462612 100,104.708498 Z"
              opacity="0.100000001"
            ></path>
            <path d="M1046,51.6521276 C1130.83045,29.328812 1279.08318,17.607883 1439,40.1656806 L1439,120 C1271.17211,77.9435312 1140.17211,55.1609071 1046,51.6521276 Z" id="Path-4" opacity="0.200000003"></path>
          </g>
          <g transform="translate(-4.000000, 76.000000)" fill="#FFFFFF" fill-rule="nonzero">
            <path
              d="M0.457,34.035 C57.086,53.198 98.208,65.809 123.822,71.865 C181.454,85.495 234.295,90.29 272.033,93.459 C311.355,96.759 396.635,95.801 461.025,91.663 C486.76,90.01 518.727,86.372 556.926,80.752 C595.747,74.596 622.372,70.008 636.799,66.991 C663.913,61.324 712.501,49.503 727.605,46.128 C780.47,34.317 818.839,22.532 856.324,15.904 C922.689,4.169 955.676,2.522 1011.185,0.432 C1060.705,1.477 1097.39,3.129 1121.236,5.387 C1161.703,9.219 1208.621,17.821 1235.4,22.304 C1285.855,30.748 1354.351,47.432 1440.886,72.354 L1441.191,104.352 L1.121,104.031 L0.457,34.035 Z"
            ></path>
          </g>
        </g>
      </svg>
    </div>
   
    
   
    <!-- Change the colour #f8fafc to match the previous section colour -->
    <svg class="wave-top" viewBox="0 0 1439 147" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
      <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g transform="translate(-1.000000, -14.000000)" fill-rule="nonzero">
          <g class="wave" fill="#f8fafc">
            <path
              d="M1440,84 C1383.555,64.3 1342.555,51.3 1317,45 C1259.5,30.824 1206.707,25.526 1169,22 C1129.711,18.326 1044.426,18.475 980,22 C954.25,23.409 922.25,26.742 884,32 C845.122,37.787 818.455,42.121 804,45 C776.833,50.41 728.136,61.77 713,65 C660.023,76.309 621.544,87.729 584,94 C517.525,105.104 484.525,106.438 429,108 C379.49,106.484 342.823,104.484 319,102 C278.571,97.783 231.737,88.736 205,84 C154.629,75.076 86.296,57.743 0,32 L0,0 L1440,0 L1440,84 Z"
            ></path>
          </g>
          <g transform="translate(1.000000, 15.000000)" fill="#FFFFFF">
            <g transform="translate(719.500000, 68.500000) rotate(-180.000000) translate(-719.500000, -68.500000) ">
              <path d="M0,0 C90.7283404,0.927527913 147.912752,27.187927 291.910178,59.9119003 C387.908462,81.7278826 543.605069,89.334785 759,82.7326078 C469.336065,156.254352 216.336065,153.6679 0,74.9732496" opacity="0.100000001"></path>
              <path
                d="M100,104.708498 C277.413333,72.2345949 426.147877,52.5246657 546.203633,45.5787101 C666.259389,38.6327546 810.524845,41.7979068 979,55.0741668 C931.069965,56.122511 810.303266,74.8455141 616.699903,111.243176 C423.096539,147.640838 250.863238,145.462612 100,104.708498 Z"
                opacity="0.100000001"
              ></path>
              <path d="M1046,51.6521276 C1130.83045,29.328812 1279.08318,17.607883 1439,40.1656806 L1439,120 C1271.17211,77.9435312 1140.17211,55.1609071 1046,51.6521276 Z" opacity="0.200000003"></path>
            </g>
          </g>
        </g>
      </g>
    </svg>
   
   
   
  </body>
</html>