newsletter-platform/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#root'
  resources :newsletters
  resources :issues
  resources :accounts
  resources :account_links
  resources :memberships
  resource :billing
  resources :login_links
  get 'dashboard', to: 'pages#dashboard'
  
  # localhost:3000
  post '/webhooks/:source', to: 'webhooks#create'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

newsletter-platform/app/models/account.rb
class Account < ApplicationRecord
  belongs_to :author, class_name: 'User'
end

newsletter-platform/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

newsletter-platform/app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :reader, class_name: 'User'
end

newsletter-platform/app/models/event.rb
class Event < ApplicationRecord
    enum status: {
        pending: 0,
        processing: 1,
        processed: 2,
        failed: 3,
    }
end

newsletter-platform/app/models/issue.rb
class Issue < ApplicationRecord
  belongs_to :newsletter
end

newsletter-platform/app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :newsletter
  belongs_to :reader, class_name: 'User'
end

newsletter-platform/app/models/newsletter.rb
class Newsletter < ApplicationRecord
  belongs_to :author, class_name: 'User'

  has_many :issues
  has_many :memberships, dependent: :destroy
end

newsletter-platform/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :trackable

  has_many :newsletters, foreign_key: :author_id, dependent: :destroy
  has_many :issues, through: :newsletters
  has_many :accounts, foreign_key: :author_id, dependent: :destroy

  has_many :memberships, foreign_key: :reader_id, dependent: :destroy
  has_many :customers, foreign_key: :reader_id, dependent: :destroy
  has_many :subscribed_newsletters, through: :memberships, source: :newsletter

  def active_subscribed_newsletters
    subscribed_newsletters.where('memberships.status = ?', 'active')
  end

  def stripe_customer_id
    if customers.empty?
      customer = Stripe::Customer.create(
        email: email,
      )
      customers.create!(stripe_customer_id: customer.id)
    end

    customers.first.stripe_customer_id
  end

  def stripe_account_id
    default_account&.stripe_account_id
  end

  def default_account
    accounts.find_by(default_account: true)
  end
end

newsletter-platform/app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authenticate_user!

  def index
    @accounts = current_user.accounts
  end

  def show
    @account = current_user.accounts.find(params[:id])
  end

  def new
  end

  def create
    country = params[:account][:country].upcase
    account = Stripe::Account.create(
      type:'express',
      country: country,
      email: current_user.email,
      capabilities: {
        card_payments: {requested: true},
        transfers: {requested: true}
      },
      business_type: 'individual',
      business_profile: {
        mcc: '5815',
        name: current_user.name,
        product_description: 'Email newsletters',
        support_email: current_user.email,
        url: 'https://mikethedev.ca',
      },
      tos_acceptance: {
        service_agreement: country == 'US' ? 'full' : 'recipient',
      }
    )

    link = Stripe::AccountLink.create(
      account: account.id,
      refresh_url: new_account_url,
      return_url: account_url(account.id),
      type: 'account_onboarding',
      collect: 'eventually_due',
    )

    current_user.accounts.create!(
      stripe_account_id: account.id,
    )

    redirect_to link.url, allow_other_host: true
  end

  def edit
  end
end

newsletter-platform/app/controllers/billings_controller.rb
class BillingsController < ApplicationController
    before_action :authenticate_user!

    def show
        # Redirect to the Stripe Customer portal
        customer_portal = Stripe::BillingPortal::Session.create(
            customer: current_user.stripe_customer_id,
            return_url: dashboard_url
        )
        redirect_to customer_portal.url, allow_other_host: true
    end

end

newsletter-platform/app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :authenticate_user!

  def index
    @issues = current_user.issues.includes(:newsletter)
  end

  def new
    @issue = Issue.new
    # @issue = Issue.new(published_at: Time.now)

  end

  def create
    @issue = current_user.issues.new(issue_params)
    if @issue.save
      redirect_to issues_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @issue = Issue.find(params[:id])
  end


  def edit
    @issue = current_user.issues.find(params[:id])
  end

  def update
    @issue = current_user.issues.find(params[:id])
    if @issue.update(issue_params)
      redirect_to issues_path
    else
      render :edit
    end
  end

  private
  def issue_params
    params.require(:issue).permit(:newsletter_id, :subject, :content, :published_at )
  end
end

newsletter-platform/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  layout 'marketing'

  def root
  end

  def dashboard
    @subscribed_newsletters = current_user.active_subscribed_newsletters
    @newsletters = Newsletter.where.not(id: @subscribed_newsletters.pluck(:id))
    @issues = Issue.where(newsletter: @subscribed_newsletters).order(created_at: :desc)

    render 'dashboard', layout: 'application'
  end
end

newsletter-platform/app/controllers/webhooks_controller.rb
class WebhooksController < ApplicationController
    skip_before_action :verify_authenticity_token

    def create
        @event = Event.create!(
            data: params.to_json,
            source: params[:source],
            status: :pending,
        )
        EventJob.perform_later(@event)
        render json: { status: :ok }
    end
end

newsletter-platform/app/helpers/account_links_helper.rb
module AccountLinksHelper
end

newsletter-platform/app/helpers/accounts_helper.rb
module AccountsHelper
end

newsletter-platform/app/helpers/application_helper.rb
module ApplicationHelper
end

newsletter-platform/app/helpers/billings_helper.rb
module BillingsHelper
end

newsletter-platform/app/helpers/issues_helper.rb
module IssuesHelper
end

newsletter-platform/app/helpers/login_links_helper.rb
module LoginLinksHelper
end

newsletter-platform/app/helpers/memberships_helper.rb
module MembershipsHelper
end

newsletter-platform/app/helpers/newsletters_helper.rb
module NewslettersHelper
end

newsletter-platform/app/helpers/pages_helper.rb
module PagesHelper
end

newsletter-platform/app/helpers/webhooks_helper.rb
module WebhooksHelper
end

newsletter-platform/app/views/accounts/edit.html.erb
<div>
  <h1 class="font-bold text-4xl">Accounts#edit</h1>
  <p>Find me in app/views/accounts/edit.html.erb</p>
</div>

newsletter-platform/app/views/accounts/index.html.erb
<div class="flex flex-col">
  <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="flex justify-center p-5 items-between gap-5">
    <div class="text-3xl text-center">
      Accounts
    </div>
  </div>
    <div class="inline-block min-w-full py-2 sm:px-6 lg:px-8">
      <div class="overflow-hidden">
        <table class="min-w-full text-center text-sm font-light">
          <thead class="border-b font-medium dark:border-neutral-500">
            <tr>
              <th scope="col" class="px-6 py-4">Stripe Account ID</th>
              <th scope="col" class="px-6 py-4"><span>Charges enabled</span></th>
              <th scope="col" class="px-6 py-4">Transfers enabled</th>
              <th scope="col" class="px-6 py-4">Onboarding complete</th>
              <span class="sr-only"></span>
            </tr>
          </thead>
          <tbody>
            <% @accounts.each do |n| %>
            <tr class="border-b dark:border-neutral-500">
              <td class="whitespace-nowrap px-6 py-4 font-medium">
                <%= n.stripe_account_id %>
              </td>
              <td class="whitespace-nowrap px-6 py-4">
                <%= n.charges_enabled %>
              </td>
              <td class="whitespace-nowrap px-6 py-4">
                <%= n.transfers_enabled %>
              </td>
              <td class="whitespace-nowrap px-6 py-4">
                
                <% if !n.details_submitted %>
                <form action="/account_links" method="POST" data-turbo="false">
                  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
                  <input type="hidden" name="account_id" value="<%= n.stripe_account_id %>">

                  <button type="submit" class="ml-5 inline-block px-4 py-2 font-semibold text-white bg-blue-500 rounded-md hover:bg-blue-600 transition duration-300 ease-in-out" >Finish onboarding </button>
                </form>

                <% else  %>
                 True
                <% end %>
              </td>
              <td class="whitespace-nowrap px-6 py-4">
                
                
                <form action="/login_links" method="POST" data-turbo="false">
                  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
                  <input type="hidden" name="account_id" value="<%= n.stripe_account_id %>">

                  <button type="submit" class="ml-5 inline-block px-4 py-2 font-semibold text-white bg-blue-500 rounded-md hover:bg-blue-600 transition duration-300 ease-in-out" >Open Dashboard</button>
                </form>

              </td>
             
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

newsletter-platform/app/views/accounts/new.html.erb
<form action="/accounts" method="POST" data-turbo="false" class="gap-5">
  <%= csrf_meta_tags %>
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <div class="flex flex-col gap-5 items-center justify-center">
    <label class="text-4xl" for="country">Country</label>
    <select
      id="country"
      name="account[country]"
      class="mt-2 block w-1/2 rounded-md border-0 py-1.5 pl-3 pr-10 text-gray-900"
    >
      <option value="US">United States</option>
      <option value="CA">Canada</option>
      <option value="MX">Mexico</option>
      <option value="IE">Ireland</option>

    </select>
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <button type="submit" class="rounded-md w- bg-indigo-600 py-1.5 px-2.5 text-sm font-semibold text-white shadow-sm hover:" >
    Create a Stripe Account
  </button>
  </div>
  
</form>

newsletter-platform/app/views/accounts/show.html.erb
<div>
  <h1 class="font-bold text-4xl">Accounts#show</h1>
  <p>Find me in app/views/accounts/show.html.erb</p>
</div>

newsletter-platform/app/views/issues/_form.html.erb
<div class="text-white">
<% path = @issue.persisted? ? issue_path(@issue) : issues_path %>

</div>

<form action="<%= path %>" method="POST" class="flex flex-col gap-6 items-center">
  <%= csrf_meta_tags %>
  <div>
    <% if @issue.persisted? %>
    <input type="hidden" name="_method" value="PATCH" />
    <% end %>
    <div class="mt-2">
      <label
        for="newsletter"
        class="text-xl font-medium text-gray-900"
        >Newsletter</label
      >
      <select
        id="newsletter"
        name="issue[newsletter_id]"
        class="mt-2 w-full rounded-md border-0 py-1.5 pl-3 pr-10"
        data-te-select-init
      >
        <% current_user.newsletters.each do |n| %>
        <option value="<%= n.id %>" <%= 'selected' if @issue.newsletter_id  == n.id %> ><%= n.title %></option>
        <% end %>
      </select>
    </div>
    <label
      for="subject"
      class="text-xl font-medium text-gray-900"
      >Subject</label
    >
    <div class="mt-2">
      <input
        type="text"
        name="issue[subject]"
        id="subject"
        value="<%= @issue.subject %>"
        placeholder="A plucky subject for your subscribers"
        class="block w-full rounded-md border-0 py-1.5 text-gray"
      />
    </div>
  </div>
  <div class="m-5 gap-6">
    <label
      for="content"
      class="block text-xl font-medium leading-6 text-gray-900"
      >Add your content</label
    >
    <div class="m-5 gap-6">
      <textarea
        rows="4"
        name="issue[content]"
        class="m-8 w-full rounded-md border border-solid text-gray-900 shadow-sm"
      ><%= @issue.content %>
    </textarea>
    </div>

    <div>
        <label for="published_at">
            Published at
        </label>
        <input type="datetime-local" name="issue[published_at]" value="<% if @issue.published_at.present? %>
        <%= @issue.published_at.strftime('%FT%T') %>
      <% else %>
       
        <%= '' %>
      <% end %>" id="published_at" />
    </div>
  </div>
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <button
    type="submit"
    class="rounded-md bg-indigo-600 py-1.5 px-2.5 text-sm font-semibold text-white shadow-sm hover: mt-4"
  >
    <% if @issue.persisted? %> Update <% else %> Create <% end %>
  </button>
</form>

newsletter-platform/app/views/issues/edit.html.erb
<%= render 'form' %>

newsletter-platform/app/views/issues/index.html.erb
<div class="flex flex-col">
  <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">

<div class="flex justify-center p-5 items-between gap-5">
    <div class="text-3xl text-center">
      Issues
    </div>
      <a href="/issues/new" class="ml-5 inline-block px-4 py-2 font-semibold text-white bg-blue-500 rounded-md hover:bg-blue-600 transition duration-300 ease-in-out">Add </a>
  </div>
    <div class="inline-block min-w-full py-2 sm:px-6 lg:px-8">
      <div class="overflow-hidden">
        <table class="min-w-full text-center text-sm font-light">
          <thead class="border-b font-medium dark:border-neutral-500">
            <tr>
              
              <th scope="col" class="px-6 py-4">Subject</th>
              <th scope="col" class="px-6 py-4"><span>Newsletter</span></th>
            </tr>
          </thead>
          <tbody>
            <% @issues.each do |n| %>
            <tr class="border-b dark:border-neutral-500">
              <td class="whitespace-nowrap px-6 py-4 font-medium">
                <%= n.subject %>
              </td>
              <td class="whitespace-nowrap px-6 py-4 font-medium">
                <%= n.newsletter.title %>
              </td>
              <td class="whitespace-nowrap px-6 py-4">
                <a href="<%= edit_issue_path(n) %>" class="ml-5 inline-block px-4 py-2 font-semibold text-white bg-blue-500 rounded-md hover:bg-blue-600 transition duration-300 ease-in-out" >Edit</a>

              </td>
            </tr>
            <% end %>
            <% if @issues.empty? %>
            Create a new issue
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

newsletter-platform/app/views/issues/new.html.erb
<%= render 'form' %>

newsletter-platform/app/views/issues/show.html.erb
<div class="flex pt-5 text-2xl justify-center">
 <%= @issue.newsletter.title %>:
 
</div>

<div class="flex italic pt-5 text-xl justify-center">
<%= @issue.subject %> <br />

</div>

<div class="flex pt-20 w-screen-1/2">
<%= @issue.content %> <br />
</div>